### ISSUE TITLE
tkc.yaml assigns public IP spaces to the cluster

### ISSUE THREAD

**Issue by nhinds** [vsphere-tmm/vsphere-with-tanzu-quick-start#1]
[manifests/tkc.yaml](https://github.com/vsphere-tmm/vsphere-with-tanzu-quick-start/blob/master/manifests/tkc.yaml) uses `193.0.2.0/16` for pod IPs and `195.51.100.0/12` for services.
- `193.0.2.0/16` is `193.0.0.0/16`, covering IPs `193.0.0.0` to `193.0.255.255`
- `195.51.100.0/12` is `195.48.0.0/12`, covering IPs `195.48.0.0` to `195.63.255.255`

These both refer to public IP blocks, and should not be assigned to private network resources. Using these IPs may result in pods or services being assigned IPs that are used for real resources on the internet, preventing the cluster from accessing those internet services.

Please use private networks when allocating IPs or networks - for IPv4, that usually means using something within `10.0.0.0/8`, `172.16.0.0/12`, or `192.168.0.0/16`, although if you consider this `.yaml` file documentation then you can use the three blocks [reserved for documentation](https://tools.ietf.org/html/rfc5737), `192.0.2.0/24`, `198.51.100.0/24`, and `203.0.113.0/24`.

The CIDR blocks you're using are quite close to the first 2 documentation blocks, but it's not safe to change `192.0.2.0/24` (reserved documentation space) to `193.0.2.0/16` (public IP space).

**Comment by mylesagray** [comment]
Good catch @nhinds - I'm checking internally, you're right I suspect - these should definitely be BOGON addresses, not public. Just need to check for unintended circumstances.

**Comment by mylesagray** [comment]
Resolved in https://github.com/vsphere-tmm/vsphere-with-tanzu-quick-start/commit/a0c6381600def0463bf409ded381db7ee12003fa
