### ISSUE TITLE
kubectl run gives error 

### ISSUE THREAD

**Issue by efex2000** [vsphere-tmm/vsphere-with-tanzu-quick-start#2]
Hi all

When i run **kubectl run -i --tty busybox --image=busybox --restart=Never -- sh**
it gives error: **error: timed out waiting for the condition**

İ tried to find what the problm was and input: **kubectl get pods** 
The pod was created but, Status is shown **imagepullbackoff**

i wrote "kubectl describe pod busybox" The base error is;

**Failed to pull image "busybox": rpc error: code = Unknown desc = failed to resolve image "docker.io/library/busybox:latest": failed to fetch anonymous token: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io: read tcp myipaddress:59158->52.55.168.20:443: read: connection reset by peer**

I searched and find related to communicate kubernetes and docker registry. But i couldnt find the accurate thing that i have to do. Do you have any ideas?

**Comment by mylesagray** [comment]
Looks like it had problems authenticating with Docker Hub anonymously, Docker introduced rate limiting as of end of last year, which breaks a lot of stuff.

It could be related to that - other times I’ve seen it automatically recover from this.

That said, I’ll update all instructions to use different images (not on Docker Hub) to get around this.

**Comment by mylesagray** [comment]
Updated.

**Comment by efex2000** [comment]
Hi 
Thanks for answer.

When i use quay.io the error transformed to another. I can go to quay.io/quay/busybox from the web browser, also i can wget and curl without problem.  

kubectl run -i --tty busybox --image=quay.io/quay/busybox --restart=Never -- sh

kubelet, tkg-cluster-01-workers-7z875-5457677d85-kss66  Failed to pull image "quay.io/quay/busybox": rpc error: code = Unknown desc = failed to resolve image "quay.io/quay/busybox:latest": no available registry endpoint: failed to do request: Head https://quay.io/v2/quay/busybox/manifests/latest: dial tcp 3.216.152.103:443: i/o timeout

**Comment by mylesagray** [comment]
Sounds like your cluster is firewalled?

Nothing wrong with the address or image (tested here).

**Comment by efex2000** [comment]
Thank you again. I am frightened that i missed something.

I prepared a jump windows machine. There is no firewall between this machine vsphere, tkg cluster and control plane VMs.

I  configured my jump machine and vcenter to access internet. I dont know any information if control plane vms or tkg cluster needs internet access or not. I didnt see any information about it.

Now i want to now  this question's answer: 

"Do control plane vms or TKG cluster require internet access  when i input "kubectl run -i --tty busybox --image=quay.io/quay/busybox --restart=Never -- sh" on the jump machine.(i am thinking only jump machine requires internet)

If at least on of them require internet access can you point which document does explain this information?

**Comment by mylesagray** [comment]
Your TKG clusters (workers and control plane nodes) all need access to the internet to pull the images - image pulls are done by the kubelet agent on each K8s node, not by the node where you run "kubectl".

vCenter doesn’t proxy docker pull requests - that’s left to the TKG clusters themselves.

It’s assumed that if you are pulling images from an external registry (i.e. not one deployed behind your corp firewall) that internet access is expected, so it’s not called out explicitly - there is specific docs if you want to deploy in an "Air-gapped environment".

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-C3048E95-6E9D-4AC3-BE96-44446D288A7D.html?hWord=N4IghgNiBcIG4GcAOALApgJzQAgO4EsAXFbQsAOwC8BXbfcwzctQkAXyA <https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-C3048E95-6E9D-4AC3-BE96-44446D288A7D.html?hWord=N4IghgNiBcIG4GcAOALApgJzQAgO4EsAXFbQsAOwC8BXbfcwzctQkAXyA> gives an overview of the networking required for a standard installation.

**Comment by efex2000** [comment]
Thanks for quick respponse.

How can i config my tkg cluster to access internet. Is there command to set proxy for internet for TKG cluster?

**Comment by mylesagray** [comment]
I would assume your networks are routable to the internet, if not - yep you can use a proxy:

https://tanzu.vmware.com/content/blog/new-proxy-support-registry-service-trust-separate-disks-vsphere-tanzu

See the “Configuring a Global Proxy” section in the below:

https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-4838C85E-398D-4461-9C4E-561FADD42A07.html

If you apply that configuration to the vSphere with Tanzu namespace, you should be able to access the internet from those clusters using your proxy.

**Comment by efex2000** [comment]
Thaks for information Mylesa
With your support i decided to use Harbor as external private registry. Now i am able to deploy basic containers
